version: "3"
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - bbs
    restart: always
  bbs:
    image: nodebb/docker
    container_name: bbs
    ports:
      - 4567:4567
    networks:
      - bbs
    restart: always
networks:
  bbs:
